package uk.ac.gla.atanaspam.network;

import uk.ac.gla.atanaspam.pcapj.IPPacket;
import uk.ac.gla.atanaspam.pcapj.TCPFlags;

import java.io.Serializable;
import java.net.InetAddress;
import java.util.Arrays;

/**
 * This class represents a packet wrapper for packets generated by pcapj
 * @author atanaspam
 * @version 0.1
 * @created 01/11/2015
 */
public class GenericPacket extends IPPacket implements Serializable{

    private static final long serialVersionUID = 0;

    String type;
    protected int src_port;
    protected int dst_port;

    protected TCPFlags flags;

    protected byte[] data;

    public int getSrc_port() {
        return src_port;
    }

    public int getDst_port() {
        return dst_port;
    }

    public TCPFlags getFlags() {
        return flags;
    }

    public byte[] getData() {
        return data;
    }

    public String getType(){return type; }




    /**
     * Initializes a Generic Packet instance out of the fields of an IPPacket.
     * @param timestamp
     * @param srcMAC
     * @param destMAC
     * @param srcIP
     * @param dstIP
     */
    public GenericPacket(long timestamp, String srcMAC, String destMAC, InetAddress srcIP, InetAddress dstIP) {

        super(timestamp, srcMAC, destMAC, srcIP, dstIP);
        this.type = "IPP";

    }

    /**
     * Initializes a Generic Packet instance out of the fields of an TCPacket.
     * @param timestamp
     * @param srcMAC
     * @param destMAC
     * @param srcIP
     * @param dstIP
     * @param src_port
     * @param dst_port
     * @param flags
     */
    public GenericPacket(long timestamp, String srcMAC, String destMAC, InetAddress srcIP, InetAddress dstIP, int src_port, int dst_port, TCPFlags flags) {

        super(timestamp, srcMAC, destMAC, srcIP, dstIP);
        this.src_port = src_port;
        this.dst_port = dst_port;
        this.flags = flags;
        this.type = "TCP";

    }

    /**
     * Initializes a Generic Packet instance out of the fields of an UDPacket.
     * @param timestamp
     * @param srcMAC
     * @param destMAC
     * @param srcIP
     * @param dstIP
     * @param src_port
     * @param dst_port
     */
    public GenericPacket(long timestamp, String srcMAC, String destMAC, InetAddress srcIP, InetAddress dstIP, int src_port, int dst_port) {

        super(timestamp, srcMAC, destMAC, srcIP, dstIP);
        this.src_port = src_port;
        this.dst_port = dst_port;
        this.type = "UDP";

    }

    /**
     * Returns a string representation of a Generic Packet depending on the actual packet type
     * @return The String representation
     */
    public String toString(){
        if (type.equals("IPP")){
            return String.format(
                    "-----PACKET-----%nTimeStamp: %d%nSRC MAC: %s%nDST MAC: %s%nSRC IP: %s%nDEST IP: %s%n",
                    this.timestamp/1000, this.sourceMacAddress, this.destMacAddress, this.src_ip.getHostAddress(),
                    this.dst_ip.getHostAddress());
        }
        else if (type.equals("UDP")){
            return String.format(
                    "-----UDP PACKET-----%nTimeStamp: %d%nSRC MAC: %s%nDST MAC: %s%nSRC IP: %s%nDEST IP: %s%nSRC PORT: %d%n" +
                            "DEST PORT: %d%n",
                    this.timestamp/1000, this.sourceMacAddress, this.destMacAddress, this.src_ip.getHostAddress(),
                    this.dst_ip.getHostAddress(), this.src_port, this.dst_port);
        }
        else if (type.equals("TCP")){
            return String.format(
                    "-----TCP PACKET-----%nTimeStamp: %d%nSRC MAC: %s%nDST MAC: %s%nSRC IP: %s%nDEST IP: %s%nSRC PORT: %d%n" +
                            "DEST PORT: %d%nFLAGS: %s%n",
                    this.timestamp/1000, this.sourceMacAddress, this.destMacAddress, this.src_ip.getHostAddress(),
                    this.dst_ip.getHostAddress(), this.src_port, this.dst_port/*, this.seqNum, this.ackNum, this.data.length*/,
                    this.flags);
        }
        else return "Unknown packet";
    }



}